### ISSUE TITLE
visualization of results

### ISSUE THREAD

**Issue by yixing333** [nateraw/Lda2vec-Tensorflow#3]
Hi nateraw, I find this extremely helpful! I'm looking to visualize the results...do you have any example or instructions to visualize the topics mix and to do prediction for a new document?  Thanks!

**Comment by nateraw** [comment]
Hey! I am planning on adding more stuff for easy visualization of results asap. As for predicting the new document, I have code for it, but it doesnt work great. Basically you have to retrain the model with the new document included. 

As for visualization, I would suggest using tensorboard! I will add a tool to easily create the meta tsv files later too so that tensorboard visualization is less labor intensive. In that, I want to include an option to name the learned topics. I'll add some TODOs when I am home, I am currently travelling. 

Will update you ASAP!

**Comment by yixing333** [comment]
Hey Nathan,

Thanks so much for the quick reply!

Regarding the prediction, there must be an easier way right (without re-training)? e.g. using model parameters to get the topic mix for a new document. I haven’t seen a straight forward way to code it though…let me know if you have any thoughts

Best,
Yixing

**Comment by nateraw** [comment]
There are other ways to potentially do it, but as far as I'm concerned, it doesnt make sense without retraining :cry:. Maybe I will be able to figure out a different way, but either way I'll upload an example ASAP

**Comment by nateraw** [comment]
Hey @yixing333! I think the best way to visualize the results would be through pyldavis, as the original author did. I will hopefully be able to push an example of this today, as I implemented something that will package up the data in the correct format.

**Comment by nateraw** [comment]
The most recent version supports pyldavis. Check out the new version of the twenty newsgroups example so you can generate something like this:

![pyldavis_example](https://user-images.githubusercontent.com/32437151/42582652-b9ae1c64-84fd-11e8-97a5-04703a3fd0e3.png)
