### ISSUE TITLE
where should I put the pre-trained glove vector?

### ISSUE THREAD

**Issue by lifinger** [nateraw/Lda2vec-Tensorflow#7]
Thanks for sharing the code, which is very clear and extremely helpful for me!!
Maybe my question is a little dumb, where should I place the pre-trained glove vectores?

Actually I tried to install pre-trained vectors from spacy website (https://spacy.io/models/), with little modification of the code, it can run now. But many warnings pop up, saying "Warning! Document 8967 broke, likely due to spaCy merge issues.More info at their github, issues #1547 and #1474". 

So I guess my modification has some problem, can you please tell me how do you handle this?

Thanks a lot!!

**Comment by nateraw** [comment]
Hey @lifinger! Im glad you like the code.

The documentation is out of date. Glove Vectors are no longer supported. I switched to google news vectors, as the original author intended. I'll see if I can get better documentation on how that all works with the pipeline, because I have my google news vectors saved right in my spacy python package folder (which is a little bit more of a pain to set up). 

I believe all you will have to do is alter the initialization of the pipeline class by passing your google news vectors to the parameter "gn_path". So, for example:

```python
SP = NlpPipeline(path_to_file, 100, gn_path="path\to\googlenews.bin")
```

I believe this solves your issue, so I'm going to go ahead and close this!
